server:
  port: 8001
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/pratice?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver,其他:com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
mybatis:
  #实体类的存放路径
  type-aliases-package: com.wzw.mynetty.dao.pojo
  mapper-locations: classpath:mapperXml/*.xml
socketIo:
  win: localhost
  linxu: 193.168.0.1
  port: 12300
