server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver,其他:com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  #实体类的存放路径
  type-aliases-package: com.wzw.springboot.dao.pojo
  mapper-locations: classpath:mapperXml/*.xml

logging:
  level:
    com.wzw.springboot.controller: debug
  file: log/app-user.log
